version: '3.9'

services:
  backend:
    restart: always
    build:
      context: .
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    # volumes:
    #   - .:/app
